apiVersion: v1
kind: Service
metadata:
  name: upring
  labels:
    component: upring
spec:
  selector:
    component: upring
  type: ClusterIP
  clusterIP: None
  ports:
  - name: swim
    port: 7799
    protocol: UDP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: upring
  labels:
    component: upring
spec:
  replicas: 5
  template:
    metadata:
      labels:
        component: upring
    spec:
      containers:
      - name: upring
        image: upring
        imagePullPolicy: Never
        ports:
        - containerPort: 7799
          name: swim
        env:
        - name: AWS_ACCESS_KEY_ID
          value: 
        - name: AWS_SECRET_ACCESS_KEY
          value: 
        - name: QUEUE_URL
          value: 
        - name: LOGDNA_KEY
          value: 